using System.Collections.Generic;
using UnityEngine;

public class BookSnippets : MonoBehaviour
{
    public static BookSnippets Instance { get; private set; }
    void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }
        Instance = this;
    }

    private Dictionary<string, string> snippets = new Dictionary<string, string>
    {
        { "book_lion", "...At that time, King Valens was reigning in Constantinople. Those Bulgarians had the intention and agreement among themselves to seek good and fertile land. A great multitude rose up from that land and from the river and came to the Hungarian and Wallachian lands. They sent word to King Valens and asked him to let them cross the Danube so that they might settle along the Danube and in Thrace. The Bulgarians took a liking to this land and promised King Valens that they would be obedient to the Greeks and Romans and would assist them in war. Valens ordered the Bulgarians to cross the Danube into Thrace and settle along the Danube and the Black Sea as far as Morava and Harsava, and to guard the borders of the Greeks against the Goths, Scythians, and Avars—which are Tatars and Hungarians. Thus, at that time, the Bulgarians crossed the river Danube and first settled along the Danube.\r\n...At that time, the Greeks did not know that the Bulgarians called themselves Bulgarians, but called them Goths and Huns. They called all peoples who came from the north ‘Goths,’ just as today they call them ‘Tatars.’\r\n...Thus the Bulgarians found good and abundant land and settled there. But they were not accustomed to obeying kings; rather, they were fierce and wild, fearless and strong in war, \n\n fierce as lions.\n\n One would go against ten without fear, just as to this day a mighty and powerful people comes forth from the north, strong in war and battle. Such were the Bulgarians in the beginning—strong and robust in war.\r\nIn the first part of Baronius, on page 567, it is written: ‘The Bulgarians are feared by the whole world, a small people, but unconquerable.’Thus the Greeks also write in their histories: ‘The Bulgarians are wild and unconquerable in war.’ And again: ‘The Bulgarian people are fierce, and they are unconquerable in wars.’\r\nThey caused much trouble for the Greeks and Romans, and for this reason they called them thus. So these Bulgarians, after a short time, rose up against the Greek lands and caused harm to the Greeks. Therefore King Valens set out with an army against them. But by God’s will, the Bulgarians and the Goths defeated Valens in battle. He fled, and they pursued him and caught up with him near Adrianople. He hid with his vizier in a barn. They set the barn on fire, and there King Valens was burned to death together with his vizier. Thus they wrote about Valens in the account of his deeds: ‘King Valens went mad and let the Goths in; they crossed the Danube and settled in Thrace. Afterwards he was defeated and burned by them.’...\r\n" },
        { "book_river", "...In the land of Moscow there is a country called Scandavia. When those who were in that country first dispersed, they were called Scandavlans.\r\n...And these Scandavlans settled there near Brandibur, and because of this name, Sandavlans, they later called that people Slavs—and so they are called to this day.\r\n...They speak the Slavic language most correctly and purely, and they use many words similar to Bulgarian ones, but now they profess the Roman faith and fight on the side of the German king.\r\n...When they had settled in that land near the Germans and the Brandeburs, at one time a great multitude of them arose and went back to the land of Moscow. But the Muscovites and the Russians did not let them enter their land, and a great war and battle broke out. There, in the war, the Slavs were victorious; they entered that land again and settled along \n\n the great river Bolga \n\n, which flows from south to north through the Muscovite state and empties into the Ocean Sea.\r\nBecause of this river Bolga, the Slavs came to be called Bulgarians—and so they are called to this day—and they remained in that land for many years and ages, until the year 328 after the birth of Christ...\r\n" },
        { "book_blood", "…In the aforementioned city (Plovdiv), as well as in the other provinces, there live many Christians who speak the Slavic language. From them, as well as from all other Christians living in his dominions, the Sultan ordinarily demands and orders that a tax be taken from their children every fourth or fifth year. Thus, whoever has four or five children has one taken from him, or, if he has more, two or all of the boys are taken.\r\nThese children are sent to Anatolia, or Asia Minor across the sea, and are distributed among the local inhabitants throughout all the towns and villages. Until they grow up, the children are employed in all kinds of physical labor and learn the Turkish language. They are called acemioğlanı [acemi oğlan].\r\nLater, when the children have grown stronger, the Sultan demands them, and those who have them must send them to Constantinople. If, in the meantime, one or more of the children have died or have been lost, the head of the household with whom they had been staying must report to the court of the town or village how they died. If he fails to do so, he must pay for the child.\r\nLater, the children are employed in the Sultan’s palace, on ships, in the gardens, in the stables, and in many other places where they are needed. Those among them who distinguish themselves as they grow older are employed in whatever they have learned. Many of them learn trades, but more of them are made into Janissaries and men who subsequently behave tyrannically toward their parents and companions.\r\nThe poor Christians who are subject to the Sultan must expect such unparalleled tyranny at any time and endure it without any objection.\r\nThis extensive quotation not only contains a detailed description of this extraordinary tax and its consequences. It is also one of many testimonies showing how a sixteenth-century observer assessed the situation of the non-Muslim population in the Ottoman state, which was compelled to surrender part of its adolescent male population through the burden known to the Ottomans as devşirme, and to the Bulgarians as the \r\n\r\n ‘blood tax’.\r\n\r\nThis cruel phenomenon, which existed in the Balkans for several centuries, has long since evolved from an object of description into an object of scholarly research. It has been studied and analyzed repeatedly in an effort to determine its nature and to illuminate its role in the history of the Ottoman Empire and in the lives of the peoples subject to it.\r\n" },
        { "book_house", "...The agreement of September 1913 established that the Bulgarian municipalities in Turkey would enjoy the same rights as the other Christian communities in the Empire. It was stipulated that Bulgarians who were Turkish subjects would retain all their movable and immovable property and would not be hindered in the exercise of their human rights or their right to property.”\r\n...The exchange of rural and urban properties was to be carried out under the supervision of the two governments and with the participation of representatives of the villages that were to be exchanged. Mixed commissions appointed by the two governments would carry out the exchange and would also determine the compensation, if any, arising from differences in the exchange between the respective entire villages and private individuals. But Turkey went even further in its disregard for the agreement by failing to implement it with regard to movable and immovable property. \r\nNot only was the Bulgarian population expelled from the whole of Turkish Thrace, but there was no exchange of property whatsoever, nor was any compensation provided, as stipulated in the annex to the agreement.\r\nThe Bulgarian government hastened to appoint the commission provided for in the agreement. After remaining virtually without work in Edirne for almost a year, however, the commission was eventually dissolved. The Bulgarian government did not dare to respond with the same measure—to expel the entire Turkish population from the newly acquired territories and \r\n\r\n confiscate its property..." },
        { "book_other1", "...But unfortunately, at that very time the Bulgarian commander from Bunarkhisar, Lieutenant N., arrived and reported that the Turkish troops had halted along the Midia–Enos border line near the village of Chakli, where the new border was to run.\r\nWhen the Bulgarian garrison in Soflu withdrew, the military authorities in the town were still urging the population, which had already set out with its carts and livestock toward Bulgaria, not to flee and to return.\r\nFinally, everyone collectively decided to send delegates to the capitals of the European states to report that the population no longer wanted Bulgarian rule.\r\nThe famous French writer Pierre Loti had also arrived from Constantinople and, among other things, was said to have expressed a desire for photographs to be taken of Turks allegedly killed by the Bulgarians during their retreat.\r\nSpecial Turkish agents then went into action, transporting the bodies of Bulgarians—men and women—who had been killed in the fields by the Turkish forces, and secretly dressing them in Turkish clothes. The chief organizer of this operation was the agent on the municipal council, Imam Ismail (38 years old, stout, blond).\r\nThe Greek newspapers, too, were competing with one another at the time in publishing accounts of Bulgarian atrocities.\r\n" },
        { "book_other2", "The Turks took them out of the hospitals and brought them to the prison. We were in three or four long rooms, about a hundred people in each. They would take these unfortunate soldiers out into the prison yard and beat them most brutally with iron rods. Their screams could be heard all the way inside the prison, and we trembled with fear and pity for these unfortunate men.\r\nAmong the most severely beaten soldiers was Aleksandar Gachev from Gabrovo, an intelligent young man. He was a medical orderly and spoke German well. They had broken his back, so afterward two people had to help him when he needed to relieve himself—he could not move on his own.\r\nThere was another soldier named Lukan Nikolov from the village of Mechet Mahala in the Berkovitsa region. He, too, had been beaten badly. Among those beaten were wounded soldiers who had been taken out of the hospitals. In particular, one Turkish çavuş [sergeant] was always waiting for a Bulgarian soldier to be brought in, and the first thing he would do was beat him.\r\nThere were many merchants from Bulgaria in the prison, like me. Among them were Ivan Sapunarov from Sliven, a representative of the tobacco factories and a merchant in colonial goods; Angel Kovachev, a petition writer; and the secretary-tax collector from the village of Bosnakoy (Edirne region), I believe his name was Kirov.\r\nIn all, nine of us were deported to Bulgaria on July 20, together with the secretary-tax collector’s wife, a girl, the wife of a man who rented an inn in Edirne, and another boy of fifteen or sixteen years of age. The Turks separated the women and the boy and took them into the forest along the road to Hibibchevo, where they raped them for three days.\r\nThere was also an officer with the soldiers. Afterward, the women and the men were held for three days in a prison in Mustafapasha and then released. The girl and the boy could barely walk when they were brought there…\r\n" },
        { "book_other3", "After the Ottomans established themselves in Thrace, the question of the ratio between Christians and Muslims within their territories became one of the principal issues of their domestic political life.\r\nFollowing the experience of all the state organizations that had preceded it in this region, the newly emerging Ottoman state united its diverse population on the basis of religion. This process had to be carried out in the course of an uninterrupted religious war, waged in the name of the worldwide establishment of the Islamic faith, but which in practice also led to a continuous increase in the Christian population.\r\nThe compulsory conversion to Islam of the youths gathered through the devşirme (the pençik system) was correctly regarded, ideologically, as a good means of furthering the objectives of this war, and, practically, as an important method for increasing the Muslim population.\r\nThe first youths incorporated into the newly established military unit were Bulgarians whom the Ottomans had taken during their campaigns in Thrace. Ottoman sources provide little information about the methods by which these Bulgarians, torn away from their families and their homeland, were transformed into soldiers of the conquerors.\r\nThe only piece of information repeated in all the chronicles is that they were sent individually to different Turkish households, where they remained for some time in order to learn the language of the conquerors and their customs and traditions. Following the formal act of conversion to Islam, this was an even more significant measure for integrating them into the Turkish environment.\r\nOnce gathered together again, they were then used to form the Janissary corps...\r\nThe social status of the first Janissaries is unknown to us, but evidently, even at this early stage, they were regarded as slaves of the ruler, constituting his lawful share of the spoils of war. The fundamental principle was their complete isolation from all other social and ethnic groups within the state, in order to ensure their total dependence on the central authority. Unlike all other military corporations in the Ottoman army, they were excluded from the sphere of landholding.\r\n" }
    };

    public bool CheckKey(string key)
    {
        if (snippets.ContainsKey(key))
            return true;
        else
            return false;
    }

    public string GetText(string key)
    {
        return snippets.GetValueOrDefault(key);
    }
}
